### ISSUE TITLE
Methods for manipulating and querying tokens

### ISSUE THREAD

**Issue by Redempt** [FenderLang/Flux#20]
We should be able to turn Token into a monad, the easiest way to do it would be to implement `IntoIterator<Item = &Token>` (and `Iter`) on `&Token`. It would also be great to have methods like `first(&self, &str) -> Option<Token>`, `children_named(&self, &'static str) -> impl Iterator<Item = &Token>` and `all_children(&self, &str) -> Iterator<Item = Token>`.

**Comment by FuzzyNovaGoblin** [comment]
- [X] IntoIterator
- [ ] all_children
- [ ] named_children
- [ ] first
